import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * Server-only content loader for "PDF Mode" — mirrors quran.ts's own
 * fs-read + in-memory-cache style exactly, so this pipeline can change
 * independently of the JSON text-content pipeline it sits alongside.
 *
 * PDF Mode shows the original scanned Mushaf pages (see PDF-CONTENT.md)
 * instead of rendered text, for zero risk of introducing a typography/
 * text error. One kind of PDF exists under public/pdf/:
 *   - public/pdf/surah/{n}.pdf — one Surah's own pages, pre-generated by
 *     scripts/pdf/generate-surah-pdfs.mjs from scripts/pdf/surah-page-map.json
 *     (a hand-verified mapping — not every Surah is guaranteed to have one
 *     yet, see getSurahPdfInfo's return type).
 * (There is no Juz-level PDF Mode — Juz Mode itself was removed; each
 * Surah's own PDF is the only PDF Mode content this app serves.)
 */

const CONTENT_DIR = path.join(process.cwd(), "src", "content", "generated");

export type SurahPdfInfo = {
  /** Relative to public/pdf/, e.g. "surah/2.pdf". */
  file: string;
  pageCount: number;
};

type PdfManifest = {
  generatedAt: string;
  surahs: Record<string, SurahPdfInfo>;
};

let manifestCache: PdfManifest | null = null;

function loadManifest(): PdfManifest | undefined {
  if (manifestCache) return manifestCache;
  try {
    const fullPath = path.join(CONTENT_DIR, "pdf-manifest.json");
    manifestCache = JSON.parse(readFileSync(fullPath, "utf-8")) as PdfManifest;
    return manifestCache;
  } catch {
    return undefined;
  }
}

/**
 * A Surah's own PDF, if it has been generated yet (`npm run pdf:generate`).
 * `undefined` means PDF Mode isn't available for this Surah — callers must
 * fall back to the normal text view, never error or show a broken page.
 */
export function getSurahPdfInfo(surahNumber: number): SurahPdfInfo | undefined {
  return loadManifest()?.surahs[String(surahNumber)];
}
