import 'package:quran_flutter/core/constants/app_language.dart';

/// Per-language transliteration of each Surah's name — Arabic script
/// stays exactly as returned by the Quran API ([SurahSummary.name]);
/// this only supplies the Latin/Telugu/Urdu-script rendering shown next
/// to it (e.g. "Al-Fatihah", never a meaning-based translation like "The
/// Opening" — see [SurahSummary.englishNameTranslation] for that,
/// intentionally unused for this purpose). No Quran API supplies Telugu
/// or Urdu transliteration, so this table is authored app data, not
/// Quran content — safe to refine independently of the Quran text/audio
/// pipeline.
///
/// Keyed 1-114 (Surah number). Urdu entries use the same Perso-Arabic
/// spelling in common use by Urdu Quran translations (distinct from the
/// Arabic Uthmani text itself); Telugu entries are a phonetic
/// transliteration in Telugu script.
const Map<int, Map<AppLanguage, String>> _surahTransliterations = {
  1: {AppLanguage.english: 'Al-Fatihah', AppLanguage.telugu: 'అల్-ఫాతిహా', AppLanguage.urdu: 'الفاتحہ'},
  2: {AppLanguage.english: 'Al-Baqarah', AppLanguage.telugu: 'అల్-బఖరహ్', AppLanguage.urdu: 'البقرہ'},
  3: {AppLanguage.english: 'Aal-E-Imran', AppLanguage.telugu: 'ఆలె ఇమ్రాన్', AppLanguage.urdu: 'آل عمران'},
  4: {AppLanguage.english: 'An-Nisa', AppLanguage.telugu: 'అన్-నిసా', AppLanguage.urdu: 'النساء'},
  5: {AppLanguage.english: "Al-Ma'idah", AppLanguage.telugu: 'అల్-మాయిదా', AppLanguage.urdu: 'المائدہ'},
  6: {AppLanguage.english: "Al-An'am", AppLanguage.telugu: 'అల్-అన్ఆమ్', AppLanguage.urdu: 'الانعام'},
  7: {AppLanguage.english: "Al-A'raf", AppLanguage.telugu: 'అల్-ఆరాఫ్', AppLanguage.urdu: 'الاعراف'},
  8: {AppLanguage.english: 'Al-Anfal', AppLanguage.telugu: 'అల్-అన్ఫాల్', AppLanguage.urdu: 'الانفال'},
  9: {AppLanguage.english: 'At-Tawbah', AppLanguage.telugu: 'అత్-తౌబా', AppLanguage.urdu: 'التوبہ'},
  10: {AppLanguage.english: 'Yunus', AppLanguage.telugu: 'యూనుస్', AppLanguage.urdu: 'یونس'},
  11: {AppLanguage.english: 'Hud', AppLanguage.telugu: 'హూద్', AppLanguage.urdu: 'ہود'},
  12: {AppLanguage.english: 'Yusuf', AppLanguage.telugu: 'యూసుఫ్', AppLanguage.urdu: 'یوسف'},
  13: {AppLanguage.english: "Ar-Ra'd", AppLanguage.telugu: 'అర్-రాద్', AppLanguage.urdu: 'الرعد'},
  14: {AppLanguage.english: 'Ibrahim', AppLanguage.telugu: 'ఇబ్రాహీమ్', AppLanguage.urdu: 'ابراہیم'},
  15: {AppLanguage.english: 'Al-Hijr', AppLanguage.telugu: 'అల్-హిజ్ర్', AppLanguage.urdu: 'الحجر'},
  16: {AppLanguage.english: 'An-Nahl', AppLanguage.telugu: 'అన్-నహ్ల్', AppLanguage.urdu: 'النحل'},
  17: {AppLanguage.english: 'Al-Isra', AppLanguage.telugu: 'అల్-ఇస్రా', AppLanguage.urdu: 'بنی اسرائیل'},
  18: {AppLanguage.english: 'Al-Kahf', AppLanguage.telugu: 'అల్-కహఫ్', AppLanguage.urdu: 'الکہف'},
  19: {AppLanguage.english: 'Maryam', AppLanguage.telugu: 'మర్యమ్', AppLanguage.urdu: 'مریم'},
  20: {AppLanguage.english: 'Ta-Ha', AppLanguage.telugu: 'తా-హా', AppLanguage.urdu: 'طٰہٰ'},
  21: {AppLanguage.english: 'Al-Anbiya', AppLanguage.telugu: 'అల్-అంబియా', AppLanguage.urdu: 'الانبیاء'},
  22: {AppLanguage.english: 'Al-Hajj', AppLanguage.telugu: 'అల్-హజ్', AppLanguage.urdu: 'الحج'},
  23: {AppLanguage.english: "Al-Mu'minun", AppLanguage.telugu: 'అల్-ముమినూన్', AppLanguage.urdu: 'المومنون'},
  24: {AppLanguage.english: 'An-Nur', AppLanguage.telugu: 'అన్-నూర్', AppLanguage.urdu: 'النور'},
  25: {AppLanguage.english: 'Al-Furqan', AppLanguage.telugu: 'అల్-ఫుర్ఖాన్', AppLanguage.urdu: 'الفرقان'},
  26: {AppLanguage.english: "Ash-Shu'ara", AppLanguage.telugu: 'అష్-షుఅరా', AppLanguage.urdu: 'الشعراء'},
  27: {AppLanguage.english: 'An-Naml', AppLanguage.telugu: 'అన్-నమల్', AppLanguage.urdu: 'النمل'},
  28: {AppLanguage.english: 'Al-Qasas', AppLanguage.telugu: 'అల్-ఖసస్', AppLanguage.urdu: 'القصص'},
  29: {AppLanguage.english: 'Al-Ankabut', AppLanguage.telugu: 'అల్-అంకబూత్', AppLanguage.urdu: 'العنکبوت'},
  30: {AppLanguage.english: 'Ar-Rum', AppLanguage.telugu: 'అర్-రూమ్', AppLanguage.urdu: 'الروم'},
  31: {AppLanguage.english: 'Luqman', AppLanguage.telugu: 'లుఖ్మాన్', AppLanguage.urdu: 'لقمان'},
  32: {AppLanguage.english: 'As-Sajdah', AppLanguage.telugu: 'అస్-సజ్దా', AppLanguage.urdu: 'السجدہ'},
  33: {AppLanguage.english: 'Al-Ahzab', AppLanguage.telugu: 'అల్-అహ్జాబ్', AppLanguage.urdu: 'الاحزاب'},
  34: {AppLanguage.english: 'Saba', AppLanguage.telugu: 'సబా', AppLanguage.urdu: 'سبا'},
  35: {AppLanguage.english: 'Fatir', AppLanguage.telugu: 'ఫాతిర్', AppLanguage.urdu: 'فاطر'},
  36: {AppLanguage.english: 'Ya-Sin', AppLanguage.telugu: 'యా-సీన్', AppLanguage.urdu: 'یٰسین'},
  37: {AppLanguage.english: 'As-Saffat', AppLanguage.telugu: 'అస్-సాఫ్ఫాత్', AppLanguage.urdu: 'الصافات'},
  38: {AppLanguage.english: 'Sad', AppLanguage.telugu: 'సాద్', AppLanguage.urdu: 'ص'},
  39: {AppLanguage.english: 'Az-Zumar', AppLanguage.telugu: 'అజ్-జుమర్', AppLanguage.urdu: 'الزمر'},
  40: {AppLanguage.english: 'Ghafir', AppLanguage.telugu: 'ఘాఫిర్', AppLanguage.urdu: 'المومن'},
  41: {AppLanguage.english: 'Fussilat', AppLanguage.telugu: 'ఫుస్సిలత్', AppLanguage.urdu: 'حم السجدہ'},
  42: {AppLanguage.english: 'Ash-Shura', AppLanguage.telugu: 'అష్-షూరా', AppLanguage.urdu: 'الشوریٰ'},
  43: {AppLanguage.english: 'Az-Zukhruf', AppLanguage.telugu: 'అజ్-జుఖ్రుఫ్', AppLanguage.urdu: 'الزخرف'},
  44: {AppLanguage.english: 'Ad-Dukhan', AppLanguage.telugu: 'అద్-దుఖాన్', AppLanguage.urdu: 'الدخان'},
  45: {AppLanguage.english: 'Al-Jathiyah', AppLanguage.telugu: 'అల్-జాథియా', AppLanguage.urdu: 'الجاثیہ'},
  46: {AppLanguage.english: 'Al-Ahqaf', AppLanguage.telugu: 'అల్-అహ్ఖాఫ్', AppLanguage.urdu: 'الاحقاف'},
  47: {AppLanguage.english: 'Muhammad', AppLanguage.telugu: 'ముహమ్మద్', AppLanguage.urdu: 'محمد'},
  48: {AppLanguage.english: 'Al-Fath', AppLanguage.telugu: 'అల్-ఫతహ్', AppLanguage.urdu: 'الفتح'},
  49: {AppLanguage.english: 'Al-Hujurat', AppLanguage.telugu: 'అల్-హుజురాత్', AppLanguage.urdu: 'الحجرات'},
  50: {AppLanguage.english: 'Qaf', AppLanguage.telugu: 'ఖాఫ్', AppLanguage.urdu: 'ق'},
  51: {AppLanguage.english: 'Adh-Dhariyat', AppLanguage.telugu: 'అజ్-జారియాత్', AppLanguage.urdu: 'الذاریات'},
  52: {AppLanguage.english: 'At-Tur', AppLanguage.telugu: 'అత్-తూర్', AppLanguage.urdu: 'الطور'},
  53: {AppLanguage.english: 'An-Najm', AppLanguage.telugu: 'అన్-నజ్మ్', AppLanguage.urdu: 'النجم'},
  54: {AppLanguage.english: 'Al-Qamar', AppLanguage.telugu: 'అల్-ఖమర్', AppLanguage.urdu: 'القمر'},
  55: {AppLanguage.english: 'Ar-Rahman', AppLanguage.telugu: 'అర్-రహ్మాన్', AppLanguage.urdu: 'الرحمٰن'},
  56: {AppLanguage.english: "Al-Waqi'ah", AppLanguage.telugu: 'అల్-వాఖియా', AppLanguage.urdu: 'الواقعہ'},
  57: {AppLanguage.english: 'Al-Hadid', AppLanguage.telugu: 'అల్-హదీద్', AppLanguage.urdu: 'الحدید'},
  58: {AppLanguage.english: 'Al-Mujadilah', AppLanguage.telugu: 'అల్-ముజాదిలా', AppLanguage.urdu: 'المجادلہ'},
  59: {AppLanguage.english: 'Al-Hashr', AppLanguage.telugu: 'అల్-హష్ర్', AppLanguage.urdu: 'الحشر'},
  60: {AppLanguage.english: 'Al-Mumtahanah', AppLanguage.telugu: 'అల్-ముమ్తహినా', AppLanguage.urdu: 'الممتحنہ'},
  61: {AppLanguage.english: 'As-Saff', AppLanguage.telugu: 'అస్-సఫ్', AppLanguage.urdu: 'الصف'},
  62: {AppLanguage.english: "Al-Jumu'ah", AppLanguage.telugu: 'అల్-జుముఅహ్', AppLanguage.urdu: 'الجمعہ'},
  63: {AppLanguage.english: 'Al-Munafiqun', AppLanguage.telugu: 'అల్-మునాఫిఖూన్', AppLanguage.urdu: 'المنافقون'},
  64: {AppLanguage.english: 'At-Taghabun', AppLanguage.telugu: 'అత్-తగాబున్', AppLanguage.urdu: 'التغابن'},
  65: {AppLanguage.english: 'At-Talaq', AppLanguage.telugu: 'అత్-తలాఖ్', AppLanguage.urdu: 'الطلاق'},
  66: {AppLanguage.english: 'At-Tahrim', AppLanguage.telugu: 'అత్-తహ్రీమ్', AppLanguage.urdu: 'التحریم'},
  67: {AppLanguage.english: 'Al-Mulk', AppLanguage.telugu: 'అల్-ముల్క్', AppLanguage.urdu: 'الملک'},
  68: {AppLanguage.english: 'Al-Qalam', AppLanguage.telugu: 'అల్-ఖలమ్', AppLanguage.urdu: 'القلم'},
  69: {AppLanguage.english: 'Al-Haqqah', AppLanguage.telugu: 'అల్-హాఖ్ఖా', AppLanguage.urdu: 'الحاقہ'},
  70: {AppLanguage.english: "Al-Ma'arij", AppLanguage.telugu: 'అల్-మఆరిజ్', AppLanguage.urdu: 'المعارج'},
  71: {AppLanguage.english: 'Nuh', AppLanguage.telugu: 'నూహ్', AppLanguage.urdu: 'نوح'},
  72: {AppLanguage.english: 'Al-Jinn', AppLanguage.telugu: 'అల్-జిన్న్', AppLanguage.urdu: 'الجن'},
  73: {AppLanguage.english: 'Al-Muzzammil', AppLanguage.telugu: 'అల్-ముజ్జమ్మిల్', AppLanguage.urdu: 'المزمل'},
  74: {AppLanguage.english: 'Al-Muddaththir', AppLanguage.telugu: 'అల్-ముద్దస్సిర్', AppLanguage.urdu: 'المدثر'},
  75: {AppLanguage.english: 'Al-Qiyamah', AppLanguage.telugu: 'అల్-ఖియామా', AppLanguage.urdu: 'القیامہ'},
  76: {AppLanguage.english: 'Al-Insan', AppLanguage.telugu: 'అద్-దహర్', AppLanguage.urdu: 'الدھر'},
  77: {AppLanguage.english: 'Al-Mursalat', AppLanguage.telugu: 'అల్-ముర్సలాత్', AppLanguage.urdu: 'المرسلات'},
  78: {AppLanguage.english: 'An-Naba', AppLanguage.telugu: 'అన్-నబా', AppLanguage.urdu: 'النبا'},
  79: {AppLanguage.english: "An-Nazi'at", AppLanguage.telugu: 'అన్-నాజిఆత్', AppLanguage.urdu: 'النازعات'},
  80: {AppLanguage.english: 'Abasa', AppLanguage.telugu: 'అబసా', AppLanguage.urdu: 'عبس'},
  81: {AppLanguage.english: 'At-Takwir', AppLanguage.telugu: 'అత్-తక్వీర్', AppLanguage.urdu: 'التکویر'},
  82: {AppLanguage.english: 'Al-Infitar', AppLanguage.telugu: 'అల్-ఇన్ఫితార్', AppLanguage.urdu: 'الانفطار'},
  83: {AppLanguage.english: 'Al-Mutaffifin', AppLanguage.telugu: 'అల్-ముతఫ్ఫిఫీన్', AppLanguage.urdu: 'المطففین'},
  84: {AppLanguage.english: 'Al-Inshiqaq', AppLanguage.telugu: 'అల్-ఇన్షిఖాఖ్', AppLanguage.urdu: 'الانشقاق'},
  85: {AppLanguage.english: 'Al-Buruj', AppLanguage.telugu: 'అల్-బురూజ్', AppLanguage.urdu: 'البروج'},
  86: {AppLanguage.english: 'At-Tariq', AppLanguage.telugu: 'అత్-తారిఖ్', AppLanguage.urdu: 'الطارق'},
  87: {AppLanguage.english: "Al-A'la", AppLanguage.telugu: 'అల్-అలా', AppLanguage.urdu: 'الاعلیٰ'},
  88: {AppLanguage.english: 'Al-Ghashiyah', AppLanguage.telugu: 'అల్-గాషియా', AppLanguage.urdu: 'الغاشیہ'},
  89: {AppLanguage.english: 'Al-Fajr', AppLanguage.telugu: 'అల్-ఫజ్ర్', AppLanguage.urdu: 'الفجر'},
  90: {AppLanguage.english: 'Al-Balad', AppLanguage.telugu: 'అల్-బలద్', AppLanguage.urdu: 'البلد'},
  91: {AppLanguage.english: 'Ash-Shams', AppLanguage.telugu: 'అష్-షమ్స్', AppLanguage.urdu: 'الشمس'},
  92: {AppLanguage.english: 'Al-Layl', AppLanguage.telugu: 'అల్-లైల్', AppLanguage.urdu: 'اللیل'},
  93: {AppLanguage.english: 'Ad-Duha', AppLanguage.telugu: 'అద్-దుహా', AppLanguage.urdu: 'الضحیٰ'},
  94: {AppLanguage.english: 'Ash-Sharh', AppLanguage.telugu: 'అష్-షర్హ్', AppLanguage.urdu: 'الشرح'},
  95: {AppLanguage.english: 'At-Tin', AppLanguage.telugu: 'అత్-తీన్', AppLanguage.urdu: 'التین'},
  96: {AppLanguage.english: 'Al-Alaq', AppLanguage.telugu: 'అల్-అలఖ్', AppLanguage.urdu: 'العلق'},
  97: {AppLanguage.english: 'Al-Qadr', AppLanguage.telugu: 'అల్-ఖద్ర్', AppLanguage.urdu: 'القدر'},
  98: {AppLanguage.english: 'Al-Bayyinah', AppLanguage.telugu: 'అల్-బయ్యినా', AppLanguage.urdu: 'البینہ'},
  99: {AppLanguage.english: 'Az-Zalzalah', AppLanguage.telugu: 'అజ్-జల్జలా', AppLanguage.urdu: 'الزلزال'},
  100: {AppLanguage.english: 'Al-Adiyat', AppLanguage.telugu: 'అల్-ఆదియాత్', AppLanguage.urdu: 'العادیات'},
  101: {AppLanguage.english: "Al-Qari'ah", AppLanguage.telugu: 'అల్-ఖారిఅహ్', AppLanguage.urdu: 'القارعہ'},
  102: {AppLanguage.english: 'At-Takathur', AppLanguage.telugu: 'అత్-తకాసుర్', AppLanguage.urdu: 'التکاثر'},
  103: {AppLanguage.english: 'Al-Asr', AppLanguage.telugu: 'అల్-అస్ర్', AppLanguage.urdu: 'العصر'},
  104: {AppLanguage.english: 'Al-Humazah', AppLanguage.telugu: 'అల్-హుమజా', AppLanguage.urdu: 'الہمزہ'},
  105: {AppLanguage.english: 'Al-Fil', AppLanguage.telugu: 'అల్-ఫీల్', AppLanguage.urdu: 'الفیل'},
  106: {AppLanguage.english: 'Quraysh', AppLanguage.telugu: 'ఖురైష్', AppLanguage.urdu: 'قریش'},
  107: {AppLanguage.english: "Al-Ma'un", AppLanguage.telugu: 'అల్-మాఊన్', AppLanguage.urdu: 'الماعون'},
  108: {AppLanguage.english: 'Al-Kawthar', AppLanguage.telugu: 'అల్-కౌసర్', AppLanguage.urdu: 'الکوثر'},
  109: {AppLanguage.english: 'Al-Kafirun', AppLanguage.telugu: 'అల్-కాఫిరూన్', AppLanguage.urdu: 'الکافرون'},
  110: {AppLanguage.english: 'An-Nasr', AppLanguage.telugu: 'అన్-నస్ర్', AppLanguage.urdu: 'النصر'},
  111: {AppLanguage.english: 'Al-Masad', AppLanguage.telugu: 'అల్-మసద్', AppLanguage.urdu: 'اللہب'},
  112: {AppLanguage.english: 'Al-Ikhlas', AppLanguage.telugu: 'అల్-ఇఖ్లాస్', AppLanguage.urdu: 'الاخلاص'},
  113: {AppLanguage.english: 'Al-Falaq', AppLanguage.telugu: 'అల్-ఫలఖ్', AppLanguage.urdu: 'الفلق'},
  114: {AppLanguage.english: 'An-Nas', AppLanguage.telugu: 'అన్-నాస్', AppLanguage.urdu: 'الناس'},
};

/// The Surah-name transliteration to show for [surahNumber] in
/// [language] — falls back to the English form (or the number itself)
/// if a lookup somehow misses.
String surahTransliterationFor(int surahNumber, AppLanguage language) {
  final entry = _surahTransliterations[surahNumber];
  if (entry == null) return 'Surah $surahNumber';
  return entry[language] ?? entry[AppLanguage.english] ?? 'Surah $surahNumber';
}
