// Assembles dist/ for Cloudflare Workers Static Assets from the Next.js
// static export (out/, built with NEXT_BASE_PATH=/quran):
//
//   out/**        -> dist/quran/**   (so /quran/_next/... maps 1:1 to files)
//   out/404.html  -> dist/404.html   (also copied to the asset root: with
//                    not_found_handling "404-page" Workers serves the nearest
//                    404.html walking up from the request path; the copy in
//                    dist/quran/ covers /quran/*, the root copy is a safety
//                    net for anything routed to this Worker outside it)
//   dist/_headers    generated here — the single source of truth for the
//                    security headers/CSP/CORS/caching that used to live in
//                    next.config.ts's headers() (unsupported with
//                    output: "export").

import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(appRoot, "out");
const distDir = path.join(appRoot, "dist");
const BASE = "/quran";

if (!existsSync(path.join(outDir, "index.html"))) {
  console.error("prepare-cf: out/index.html not found — run `npm run build:cf` (not this script alone).");
  process.exit(1);
}
if (!existsSync(path.join(outDir, "404.html"))) {
  console.error("prepare-cf: out/404.html missing — the branded not-found page was not emitted.");
  process.exit(1);
}

rmSync(distDir, { recursive: true, force: true });
mkdirSync(path.join(distDir, "quran"), { recursive: true });
cpSync(outDir, path.join(distDir, "quran"), { recursive: true });
cpSync(path.join(outDir, "404.html"), path.join(distDir, "404.html"));

// --- _headers -------------------------------------------------------------
const csp = [
  "default-src 'self'",
  // 'unsafe-inline' scripts: required for the App Router's inline RSC
  // bootstrap <script> tags in a statically generated site (no nonces
  // possible) — without them nothing on the page hydrates.
  "script-src 'self' 'unsafe-inline'",
  // React inline style={{...}} is used throughout the codebase.
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  // cdn.islamic.network: per-Ayah recitation (lib/content/reciters.ts).
  // audio.iqraspace.org: Listening Mode whole-Surah files from the Flutter
  // app's dedicated R2 bucket (lib/content/listeningAudio.ts).
  "media-src 'self' https://cdn.islamic.network https://audio.iqraspace.org",
  // api.alquran.cloud: opt-in live Tajweed coloring (lib/content/tajweedApi.ts).
  "connect-src 'self' https://api.alquran.cloud",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");

const securityHeaders = {
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
  "Content-Security-Policy": csp,
};

const block = (pattern, headers) =>
  `${pattern}\n${Object.entries(headers)
    .map(([k, v]) => `  ${k}: ${v}`)
    .join("\n")}\n`;

// Cloudflare applies EVERY matching rule (a header set by several rules is
// joined with ", "), so each path gets Cache-Control from exactly one rule.
// The catch-all /quran/* carries only the security headers; caching is set
// per prefix below, with HTML routes listed explicitly.
const revalidate = { "Cache-Control": "public, max-age=0, must-revalidate" };
const parts = [
  "# Generated by scripts/prepare-cf.mjs — do not edit by hand.\n",
  block(`${BASE}/*`, securityHeaders),
  // Hashed build assets: immutable for a year.
  block(`${BASE}/_next/static/*`, { "Cache-Control": "public, max-age=31536000, immutable" }),
  // Per-Surah PDFs: public, fetched cross-origin by the Learning app's pdf.js.
  block(`${BASE}/pdf/*`, {
    "Access-Control-Allow-Origin": "*",
    "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
  }),
  // Un-hashed static assets: moderate caching with revalidation.
  block(`${BASE}/pdf-worker/*`, { "Cache-Control": "public, max-age=86400, must-revalidate" }),
  block(`${BASE}/brand/*`, { "Cache-Control": "public, max-age=86400, must-revalidate" }),
  block(`${BASE}/search-index.json`, { "Cache-Control": "public, max-age=3600, must-revalidate" }),
  // Extensionless generated files: Cloudflare cannot infer a type, so set it.
  ...["icon", "apple-icon", "opengraph-image"].map((n) =>
    block(`${BASE}/${n}`, { "Content-Type": "image/png", "Cache-Control": "public, max-age=86400, must-revalidate" }),
  ),
  block(`${BASE}/manifest.webmanifest`, {
    "Content-Type": "application/manifest+json",
    "Cache-Control": "public, max-age=86400, must-revalidate",
  }),
  block(`${BASE}/sitemap.xml`, { "Cache-Control": "public, max-age=3600, must-revalidate" }),
  // HTML pages + their RSC payload files: short cache + revalidate (content
  // only changes on deploy).
  ...[BASE, `${BASE}/`, `${BASE}/surah`, `${BASE}/surah/*`, `${BASE}/page`, `${BASE}/page/*`,
    `${BASE}/search`, `${BASE}/bookmarks`, `${BASE}/404.html`].map((p) => block(p, revalidate)),
];
writeFileSync(path.join(distDir, "_headers"), parts.join("\n"));

// --- stats ----------------------------------------------------------------
let files = 0;
let bytes = 0;
let biggest = { size: 0, file: "" };
(function walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else {
      const size = statSync(full).size;
      files++;
      bytes += size;
      if (size > biggest.size) biggest = { size, file: path.relative(distDir, full) };
    }
  }
})(distDir);
console.log(
  `prepare-cf: dist/ ready — ${files} files, ${(bytes / 1048576).toFixed(1)} MiB, largest ${biggest.file} (${(biggest.size / 1048576).toFixed(1)} MiB)`,
);
if (files > 20000) console.warn("prepare-cf: WARNING — over the 20,000-file free-plan limit.");
if (biggest.size > 25 * 1048576) console.warn("prepare-cf: WARNING — a file exceeds the 25 MiB asset limit.");
